# This is a basic workflow to help you get started with Actions

name: hourly_sync_test

# Controls when the action will run. 
on:
  schedule:
    - cron: '*/60 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Dependencies
        run: |
          echo "installing dependencies/pacman-utils"
          sudo apt-get update
          sudo apt-get install ksh curl
          wget https://github.com/ThePoorPilot/pacman-utils/releases/download/5.2.2-2_2.31-0/pacman-utils_5.2.2-2_amd64.deb
          sudo apt-get install -f ./pacman-utils_5.2.2-2_amd64.deb
      - name: download_pkgs
        run: |
          echo "starting download process"
          git clone https://github.com/ThePoorPilot/manjaro-removed-pkgs.git
          cd ./manjaro-removed-pkgs
          ./run.sh
          cd ./packages
          echo "FILES_EXIST=$(ls -1 *.pkg.tar.zst 2>/dev/null | wc -l)" >> $GITHUB_ENV
          cd ../
          cd ../
      - name: repo-add
        if: ${{ env.FILES_EXIST > '0' }}
        run: |
          cd ./manjaro-removed-pkgs/packages
          repo-add ./manjaro-removed-pkgs.db.tar.gz *.pkg.tar.zst
          cd ../
          cd ../
      - name: upload_pkgs
        if: ${{ env.FILES_EXIST > '0' }}
        run: |
          echo "${{ secrets.SECRET_TOKEN }}" > token.txt
          cd ./manjaro-removed-pkgs
          gh auth login --with-token < ../token.txt
          gh release upload -R github.com/ThePoorPilot/manjaro-removed-pkgs x86_64 ./packages/* --clobber
          rm ../token.txt
          cd ../
      - name: Generate files_to_delete.txt
        if: ${{ env.FILES_EXIST > '0' }}
        run: |
          cd ./manjaro-removed-pkgs
          ./clean_repo.sh
          echo "REMOVE_FROM_REL<<EOF" >> $GITHUB_ENV
          echo "$(cat ./files_to_delete.txt)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          cd ../
      - name: Delete old packages
        if: ${{ env.FILES_EXIST > '0' }}
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          tag: x86_64 # This may also be of the form 'refs/tags/staging'
          # 3. multiple names/globs, one per line
          assets: | 
            ${{ env.REMOVE_FROM_REL }}


#      - name: upload_pkgs(old)
#        run: |
#          cd ./manjaro-removed-pkgs
#          echo "adding ssh key for sourceforge"
#          mkdir ~/.ssh/
#          ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
#          echo "uploading packages"
#          SSHPASS="${{ secrets.PASSWORD }}" ./upload.sh
