# This is a basic workflow to help you get started with Actions

name: hourly_sync_test

# Controls when the action will run. 
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Dependencies
        run: |
          echo "installing dependencies/pacman-utils"
          sudo apt-get update
          sudo apt-get install sshpass ksh
          wget https://github.com/ThePoorPilot/pacman-utils/releases/download/5.2.2-2_2.31-0/pacman-utils_5.2.2-2_amd64.deb
          sudo apt-get install -f ./pacman-utils_5.2.2-2_amd64.deb
      - name: download_pkgs
        run: |
          echo "starting download process"
          git clone https://github.com/ThePoorPilot/manjaro-removed-pkgs.git
          cd ./manjaro-removed-pkgs
          ./run.sh
          cd ../
      - name: repo-add
        run: |
          cd ./manjaro-removed-pkgs/packages
          repo-add ./manjaro-removed-pkgs.db.tar.gz *.pkg.tar.zst
          cd ../
          cd ../
      - name: upload_pkgs
        run: |
          echo "${{ secrets.SECRET_TOKEN }}" > token.txt
          cd ./manjaro-removed-pkgs
          gh auth login --with-token < ../token.txt
          gh release create -R github.com/ThePoorPilot/manjaro-removed-pkgs x86_64 ./packages/* -n "A repo contained within a release!" -t "manjaro-removed-pkgs"
          rm ../token.txt
          
